# Make summary plots of the titers of different strains against human sera

## Setup and read data

In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/fh/fast/bloom_j/software/miniforge3/envs/seqneut-pipeline/lib/python3.13/site-packages', '/fh/fast/bloom_j/computational_notebooks/jbloom/2025/flu-seqneut-2025/seqneut-pipeline', '/fh/fast/bloom_j/computational_notebooks/jbloom/2025/flu-seqneut-2025', '/fh/fast/bloom_j/software/miniforge3/envs/seqneut-pipeline/bin', '/fh/fast/bloom_j/software/miniforge3/envs/seqneut-pipeline/lib/python3.13', '/fh/fast/bloom_j/software/miniforge3/envs/seqneut-pipeline/lib/python3.13/lib-dynload', '/fh/fast/bloom_j/software/miniforge3/envs/seqneut-pipeline/lib/python3.13/site-packages', '/home/jbloom/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpe7v59z0g/file/fh/fast/bloom_j/computational_notebooks/jbloom/2025/flu-seqneut-2025/notebooks', '/fh/fast/bloom_j/computational_notebooks/jbloom/2025/flu-seqneut-2025/notebooks']);import pickle;from snakemake import script;script.snakemake = pickle.loads(b'\x80\x04\x95a:\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c3results/aggregated_analyses/human_sera_metadata.csv\x94\x8c1results/aggregated_analyses/human_sera_titers.csv\x94\x8cBdata/viral_libraries/flu-seqneut-2025-barcode-to-strain_actual.csv\x94\x8c4data/viral_libraries/flu-seqneut-2025_plot_order.csv\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\x0cmetadata_csv\x94K\x00N\x86\x94\x8c\ntiters_csv\x94K\x01N\x86\x94\x8c\tvirus_csv\x94K\x02N\x86\x94\x8c\x17viral_strain_plot_order\x94K\x03N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x1bh\x06\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x1bsbh\x1ch\x1e)\x81\x94}\x94h!h\x1csbh\x11h\nh\x13h\x0bh\x15h\x0ch\x17h\rub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8c>results/aggregated_analyses/human_sera_titers_H3N2_median.html\x94a}\x94(h\x0f}\x94\x8c\x11median_titer_plot\x94K\x00N\x86\x94sh\x19]\x94(h\x1bh\x1ceh\x1bh\x1e)\x81\x94}\x94h!h\x1bsbh\x1ch\x1e)\x81\x94}\x94h!h\x1csbh+h(ub\x8c\r_params_store\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94(}\x94(\x8c\x1fA/Croatia/10136RV/2023-egg_H3N2\x94\x8c\x1b2025-2026 egg-based vaccine\x94\x8c!A/DistrictOfColumbia/27/2023_H3N2\x94\x8c\x1c2025-2026 cell-based vaccine\x94\x8c!A/Victoria/4897/2022_IVR-238_H1N1\x94\x8c\x1b2025-2026 egg-based vaccine\x94\x8c\x18A/Wisconsin/67/2022_H1N1\x94\x8c\x1c2025-2026 cell-based vaccine\x94\x8c\x16A/Thailand/8/2022_H3N2\x94\x8c\x1b2024-2025 egg-based vaccine\x94\x8c\x1cA/Massachusetts/18/2022_H3N2\x94\x8c\x1c2024-2025 cell-based vaccine\x94u}\x94(\x8c\x0ctiter_cutoff\x94K\x8c\x8c\x10min_frac_strains\x94G?\xe9\x99\x99\x99\x99\x99\x9a\x8c\rmin_frac_sera\x94G?\xe9\x99\x99\x99\x99\x99\x9a\x8c\x0fmin_frac_action\x94\x8c\x04drop\x94ue}\x94(h\x0f}\x94(\x8c\x16recent_vaccine_strains\x94K\x00N\x86\x94\x8c\x17human_sera_plots_params\x94K\x01N\x86\x94uh\x19]\x94(h\x1bh\x1ceh\x1bh\x1e)\x81\x94}\x94h!h\x1bsbh\x1ch\x1e)\x81\x94}\x94h!h\x1csbhKh6hMhCub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94}\x94(h\x0f}\x94h\x19]\x94(h\x1bh\x1ceh\x1bh\x1e)\x81\x94}\x94h!h\x1bsbh\x1ch\x1e)\x81\x94}\x94h!h\x1csbub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01\x8c\x04/tmp\x94e}\x94(h\x0f}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94uh\x19]\x94(h\x1bh\x1ceh\x1bh\x1e)\x81\x94}\x94h!h\x1bsbh\x1ch\x1e)\x81\x94}\x94h!h\x1csbhiK\x01hkK\x01hmhfub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94\x8c8results/aggregated_analyses/plot_human_sera_titers.ipynb\x94a}\x94(h\x0f}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x19]\x94(h\x1bh\x1ceh\x1bh\x1e)\x81\x94}\x94h!h\x1bsbh\x1ch\x1e)\x81\x94}\x94h!h\x1csbh{hxub\x8c\x06config\x94}\x94(\x8c\x16recent_vaccine_strains\x94h6\x8c\x1chuman_sera_groups_to_exclude\x94]\x94(\x8c\x03FCI\x94\x8c\x05pilot\x94e\x8c\x15human_sera_to_exclude\x94]\x94\x8c\x17human_sera_plots_params\x94hC\x8c\x10seqneut-pipeline\x94\x8c\x10seqneut-pipeline\x94\x8c\x04docs\x94\x8c\x04docs\x94\x8c\x0bdescription\x94X\x1b\x01\x00\x00# Sequencing-based neutralization assays using human serum samples collected in late 2024-2025 and combined pdmH1N1 and H3N2 influenza library\n\nThe numerical data and computer code are at [https://github.com/jbloomlab/flu-seqneut-2025](https://github.com/jbloomlab/flu-seqneut-2025)\n\x94\x8c\x0fviral_libraries\x94}\x94(\x8c!flu-seqneut-2025_library_designed\x94\x8cDdata/viral_libraries/flu-seqneut-2025-barcode-to-strain_designed.csv\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8cBdata/viral_libraries/flu-seqneut-2025-barcode-to-strain_actual.csv\x94u\x8c\x17viral_strain_plot_order\x94\x8c4data/viral_libraries/flu-seqneut-2025_plot_order.csv\x94\x8c\x12neut_standard_sets\x94}\x94\x8c\x08loes2023\x94\x8c3data/neut_standard_sets/loes2023_neut_standards.csv\x94s\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\x08upstream\x94\x8c\x1cCCTACAATGTCGGATTTGTATTTAATAG\x94\x8c\ndownstream\x94\x8c\x00\x94\x8c\x04minq\x94K\x14\x8c\x11upstream_mismatch\x94K\x04\x8c\x0ebc_orientation\x94\x8c\x02R2\x94u\x8c#default_process_plate_qc_thresholds\x94}\x94(\x8c\x1bavg_barcode_counts_per_well\x94M\xf4\x01\x8c\x1fmin_neut_standard_frac_per_well\x94G?tz\xe1G\xae\x14{\x8c"no_serum_per_viral_barcode_filters\x94}\x94(\x8c\x08min_frac\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x0fmax_fold_change\x94K\x04\x8c\tmax_wells\x94K\x02u\x8c!per_neut_standard_barcode_filters\x94}\x94(\x8c\x08min_frac\x94G?tz\xe1G\xae\x14{\x8c\x0fmax_fold_change\x94K\x04\x8c\tmax_wells\x94K\x02u\x8c min_neut_standard_count_per_well\x94M\xe8\x03\x8c)min_no_serum_count_per_viral_barcode_well\x94Kd\x8c+max_frac_infectivity_per_viral_barcode_well\x94K\x03\x8c)min_dilutions_per_barcode_serum_replicate\x94K\x06u\x8c%default_process_plate_curvefit_params\x94}\x94(\x8c\x18frac_infectivity_ceiling\x94K\x01\x8c\x06fixtop\x94]\x94(G?\xe3333333K\x01e\x8c\tfixbottom\x94K\x00\x8c\x08fixslope\x94]\x94(G?\xe9\x99\x99\x99\x99\x99\x9aK\neu\x8c!default_process_plate_curvefit_qc\x94}\x94(\x8c\x1dmax_frac_infectivity_at_least\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0fgoodness_of_fit\x94}\x94(\x8c\x06min_R2\x94G?\xe0\x00\x00\x00\x00\x00\x00\x8c\x08max_RMSD\x94G?\xc3333333u\x8c#serum_replicates_ignore_curvefit_qc\x94]\x94\x8c+barcode_serum_replicates_ignore_curvefit_qc\x94]\x94u\x8c\x16default_serum_titer_as\x94\x8c\x08midpoint\x94\x8c\x1bdefault_serum_qc_thresholds\x94}\x94(\x8c\x0emin_replicates\x94K\x01\x8c\x1bmax_fold_change_from_median\x94K\x06\x8c\x11viruses_ignore_qc\x94]\x94u\x8c\x16sera_override_defaults\x94}\x94\x8c\x06plates\x94}\x94(\x8c\nplate0_1-8\x94}\x94(\x8c\x05group\x94\x8c\x05pilot\x94\x8c\x04date\x94\x8c\x08datetime\x94\x8c\x04date\x94\x93\x94C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c%data/plates/2025-07-23_plate0_1-8.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x0eplate0_1_to_16\x94}\x94(\x8c\x05group\x94\x8c\x05pilot\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c&data/plates/2025-07-23_plate0_1-16.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x0eplate0_1_to_24\x94}\x94(\x8c\x05group\x94\x8c\x05pilot\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c&data/plates/2025-07-23_plate0_1-24.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x0eplate0_1_to_32\x94}\x94(\x8c\x05group\x94\x8c\x05pilot\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c&data/plates/2025-07-23_plate0_1-32.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate1\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2024-07-23_plate1.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06ATCGAT\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate2\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2024-07-23_plate2.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06TGACGC\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x08plate1-2\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x07\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c#data/plates/2025-08-11_plate1-2.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06ATCGAT\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x08plate2-2\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x07\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c#data/plates/2025-08-11_plate2-2.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06TGACGC\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate3\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x07\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2025-08-11_plate3.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06CAGTTG\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate4\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x07\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2025-08-11_plate4.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GTCTAA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate5\x94}\x94(\x8c\x05group\x94\x8c\x04UWMC\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x0c\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2025-08-12_plate5.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate6\x94}\x94(\x8c\x05group\x94\x8c\x03FCI\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x0c\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2025-08-12_plate6.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06ATCGAT\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\nplate7_FCI\x94}\x94(\x8c\x05group\x94\x8c\x03FCI\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x0c\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c%data/plates/2025-08-12_plate7_FCI.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06TGACGC\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\nplate7_SCH\x94}\x94(\x8c\x05group\x94\x8c\x03SCH\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x0c\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c%data/plates/2025-08-12_plate7_SCH.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06TGACGC\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate8\x94}\x94(\x8c\x05group\x94\x8c\x03SCH\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x0c\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2025-08-12_plate8.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06CAGTTG\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x06plate9\x94}\x94(\x8c\x05group\x94\x8c\x03SCH\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\r\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c!data/plates/2025-08-13_plate9.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GTCTAA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x07plate10\x94}\x94(\x8c\x05group\x94\x8c\x03SCH\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\r\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c"data/plates/2025-08-13_plate10.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06ACGCTG\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x07plate11\x94}\x94(\x8c\x05group\x94\x8c\x03SCH\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\r\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c"data/plates/2025-08-13_plate11.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06TATAGC\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x0bplate12_SCH\x94}\x94(\x8c\x05group\x94\x8c\x03SCH\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\r\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c&data/plates/2025-08-13_plate12_SCH.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06CGAGCT\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\rplate12_EPIHK\x94}\x94(\x8c\x05group\x94\x8c\x05EPIHK\x94\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\r\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c\x1fflu-seqneut-2025_library_actual\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c(data/plates/2025-08-13_plate12_EPIHK.csv\x94\x8c\x0cmanual_drops\x94}\x94\x8c\rqc_thresholds\x94}\x94(h\xaaM\xf4\x01h\xabG?tz\xe1G\xae\x14{h\xac}\x94(h\xaeG?\x1a6\xe2\xeb\x1cC-h\xafK\x04h\xb0K\x02uh\xb1}\x94(h\xb3G?tz\xe1G\xae\x14{h\xb4K\x04h\xb5K\x02uh\xb6M\xe8\x03h\xb7Kdh\xb8K\x03h\xb9K\x06u\x8c\x0fcurvefit_params\x94}\x94(h\xbcK\x01h\xbdh\xbeh\xbfK\x00h\xc0h\xc1u\x8c\x0bcurvefit_qc\x94}\x94(h\xc4G\x00\x00\x00\x00\x00\x00\x00\x00h\xc5}\x94(h\xc7G?\xe0\x00\x00\x00\x00\x00\x00h\xc8G?\xc3333333uh\xc9h\xcah\xcbh\xccu\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06CGAGCT\x94\x8c\x12upstream2_mismatch\x94K\x01uuu\x8c\x14miscellaneous_plates\x94}\x94(\x8c\x1520250716_initial_pool\x94}\x94(\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x10\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c!flu-seqneut-2025_library_designed\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c5data/miscellaneous_plates/2025-07-16_initial_pool.csv\x94\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x1620250723_balanced_pool\x94}\x94(\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c!flu-seqneut-2025_library_designed\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c8data/miscellaneous_plates/2025-07-23_balanced_repool.csv\x94\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c(20250723_H3_and_partial_H1_balanced_pool\x94}\x94(\x8c\x04date\x94h\xe0C\x04\x07\xe9\x07\x17\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c!flu-seqneut-2025_library_designed\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8cJdata/miscellaneous_plates/2025-07-23_H3_and_partial_H1_balanced_repool.csv\x94\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uu\x8c\x1620250807_balanced_pool\x94}\x94(\x8c\x04date\x94h\xe0C\x04\x07\xe9\x08\x07\x94\x85\x94R\x94\x8c\rviral_library\x94\x8c!flu-seqneut-2025_library_designed\x94\x8c\x11neut_standard_set\x94\x8c\x08loes2023\x94\x8c\x0bsamples_csv\x94\x8c8data/miscellaneous_plates/2025-08-07_balanced_repool.csv\x94\x8c\x1eillumina_barcode_parser_params\x94}\x94(\x8c\tupstream2\x94\x8c\x06GCTACA\x94\x8c\x12upstream2_mismatch\x94K\x01uuuu\x8c\x04rule\x94\x8c\x16plot_human_sera_titers\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cO/fh/fast/bloom_j/computational_notebooks/jbloom/2025/flu-seqneut-2025/notebooks\x94ub.');del script;from snakemake.logging import logger;from snakemake.script import snakemake;import os; os.chdir(r'/fh/fast/bloom_j/computational_notebooks/jbloom/2025/flu-seqneut-2025');
######## snakemake preamble end #########

In [2]:
import altair as alt

import pandas as pd

_ = alt.data_transformers.disable_max_rows()

Get variables from `snakemake`:

In [3]:
metadata_csv = snakemake.input.metadata_csv
titers_csv = snakemake.input.titers_csv
virus_csv = snakemake.input.virus_csv
viral_strain_plot_order_csv = snakemake.input.viral_strain_plot_order
recent_vaccine_strains = snakemake.params.recent_vaccine_strains
human_sera_plots_params = snakemake.params.human_sera_plots_params

In [4]:
metadata_all = pd.read_csv(metadata_csv)
print(f"Read {len(metadata_all)=} for sera from {metadata_csv=}")

titers_all = pd.read_csv(titers_csv)
print(f"\nRead {len(titers_all)=} titers from {titers_csv=}")
assert set(titers_all["serum"]) == set(metadata_all["serum"])

viruses_all = (
    pd.read_csv(virus_csv)
    [["strain", "subtype", "strain_type"]]
    .drop_duplicates()
    .rename(columns={"strain": "virus"})
)
assert set(titers_all["virus"]).issubset(viruses_all["virus"])
print(f"\nRead {len(viruses_all)=} viruses from {virus_csv=}")

Read len(metadata_all)=114 for sera from metadata_csv='results/aggregated_analyses/human_sera_metadata.csv'

Read len(titers_all)=15399 titers from titers_csv='results/aggregated_analyses/human_sera_titers.csv'

Read len(viruses_all)=146 viruses from virus_csv='data/viral_libraries/flu-seqneut-2025-barcode-to-strain_actual.csv'

## Get fraction of sera and viruses with titers
Look at the fraction of sera and viruses with titers.
We generally may want to drop sera that lack titers for many viruses, and viruses that lack titers for many sera.
Depending on `min_frac_action` (specified in configuration), we either raise an error if any sera or viruses are below the fractions specified in the configuration, or drop any sera or titers below these fractions.
In general for production runs you may want to raise an error and filter these at an upstream step.

In [5]:
min_frac_action = human_sera_plots_params["min_frac_action"]

titers = titers_all.copy()
metadata = metadata_all.copy()
viruses = viruses_all.copy()

for min_frac_type, vals, frac_vals, col, frac_var in [
    ("min_frac_strains", set(metadata["serum"]), set(viruses["virus"]), "serum", "virus"),
    ("min_frac_sera", set(viruses["virus"]), set(metadata["serum"]), "virus", "serum"),
]:
    min_frac = human_sera_plots_params[min_frac_type]
    print(f"\nChecking for {min_frac_type=} at cutoff of {min_frac=}")
    frac_df = (
        titers
        .groupby(col, as_index=False)
        .aggregate(n_w_titers=pd.NamedAgg(col, "count"))
        .assign(frac_w_titers=lambda x: x["n_w_titers"] / len(frac_vals))
    )
    frac_df = pd.concat(
        [
            frac_df,
            pd.DataFrame(
                {
                    col: [v for v in vals if v not in set(frac_df[col])],
                    "n_w_titers": 0,
                    "frac_w_titers": 0.0,
                }
            )
        ],
        ignore_index=True,
    )
    assert len(frac_df) == len(vals)
    assert (frac_df["frac_w_titers"] <= 1).all()

    frac_df["below_cutoff"] = frac_df["frac_w_titers"] < min_frac

    frac_chart = (
        alt.Chart(frac_df)
        .encode(
            alt.X(
                "frac_w_titers",
                title=f"fraction {frac_var} with titers",
                scale=alt.Scale(domain=[0, 1]),
            ),
            alt.Y(col, sort=alt.SortField("frac_w_titers", order="descending")),
            alt.Fill("below_cutoff", title=f"below cutoff of {min_frac_type} = {min_frac}"),
            tooltip=[col, "n_w_titers", alt.Tooltip("frac_w_titers", format=".3f")],
        )
        .mark_bar()
        .properties(
            height=alt.Step(11),
            width=150,
            title=f"{frac_var} with titers for each {col}",
        )
        .configure_axis(labelLimit=500)
        .configure_legend(titleLimit=500)
    )

    display(frac_chart)

    below_frac = set(frac_df.query("below_cutoff")[col])
    print(f"Overall, {len(below_frac)} {col} have titers for less then {min_frac} {frac_var}")
    display(frac_df.query("below_cutoff").sort_values("frac_w_titers").reset_index(drop=True))

    if min_frac_action == "raise":
        raise ValueError(frac_df.query("below_cutoff").sort_values("frac_w_titers").reset_index(drop=True))
    elif min_frac_action == "drop":
        print(f"Dropping these {col}")
        titers = titers[~titers[col].isin(below_frac)]
        if col == "serum":
            metadata = metadata[~metadata[col].isin(below_frac)]
        if col == "virus":
            viruses = viruses[~viruses[col].isin(below_frac)]
    else:
        raise ValueError(f"invalid {min_frac_action=}")

print(
    f"\nAfter any filtering:"
    f"\n {len(titers)=} / {len(titers_all)=}"
    f"\n {len(viruses)=} / {len(viruses_all)=}"
    f"\n {len(metadata)=} / {len(metadata_all)=}"
)

Checking for min_frac_type='min_frac_strains' at cutoff of min_frac=0.8

alt.Chart(...)

Overall, 8 serum have titers for less then 0.8 virus

     serum  n_w_titers  frac_w_titers  below_cutoff
0  UWMC-45          54       0.369863          True
1  UWMC-47          65       0.445205          True
2  UWMC-52          66       0.452055          True
3  UWMC-53          95       0.650685          True
4  UWMC-55         106       0.726027          True
5  UWMC-46         108       0.739726          True
6   SCH_26         109       0.746575          True
7  UWMC-48         115       0.787671          True

Dropping these serum

Checking for min_frac_type='min_frac_sera' at cutoff of min_frac=0.8

alt.Chart(...)

Overall, 5 virus have titers for less then 0.8 serum

                             virus  n_w_titers  frac_w_titers  below_cutoff
0          A/Brisbane/59/2007_H1N1           0            0.0          True
1         A/Perth/16/2009_egg_H3N2           0            0.0          True
2             A/Perth/16/2009_H3N2           0            0.0          True
3          A/Brisbane/10/2007_H3N2           0            0.0          True
4  A/Brisbane/02/2018_IVR-190_H1N1           0            0.0          True

Dropping these virus

After any filtering:
 len(titers)=14681 / len(titers_all)=15399
 len(viruses)=141 / len(viruses_all)=146
 len(metadata)=106 / len(metadata_all)=114

## Plot age and collection distributions of sera

In [6]:
metadata

,group,serum,collection_date_numerical,age_years,sex,collection_date_string,age_string,exposure_info
0,EPIHK,EPIHK_1,2025-04-01,14.5,F,April-2025,10to19,"Received 2024/25 NH vaccine: Yes, Received 202..."
1,EPIHK,EPIHK_2,2025-04-01,14.5,F,April-2025,10to19,"Received 2024/25 NH vaccine: Yes, Received 202..."
2,EPIHK,EPIHK_3,2025-03-01,14.5,M,March-2025,10to19,"Received 2024/25 NH vaccine: No, Received 2023..."
3,EPIHK,EPIHK_4,2025-04-01,14.5,F,April-2025,10to19,"Received 2024/25 NH vaccine: Yes, Received 202..."
4,EPIHK,EPIHK_5,2025-03-01,14.5,F,March-2025,10to19,"Received 2024/25 NH vaccine: No, Received 2023..."
...,...,...,...,...,...,...,...,...
108,UWMC,UWMC-54,2025-04-01,19.0,F,April-2025,19,na
110,UWMC,UWMC-6,2025-03-01,43.0,M,March-2025,43,na
111,UWMC,UWMC-7,2025-03-01,49.0,M,March-2025,49,na
112,UWMC,UWMC-8,2025-03-01,27.0,M,March-2025,27,na
113,UWMC,UWMC-9,2025-03-01,42.0,M,March-2025,42,na

In [13]:
sera_base = (
    alt.Chart(
        metadata[["group", "serum", "collection_date_numerical", "age_years"]]
        .assign(
            n=lambda x: x.groupby("group")["serum"].transform("count"),
            group=lambda x: x["group"] + " (n=" + x["n"].astype(str) + ")",
        )
        .drop(columns="n")
    )
    .encode(alt.Row("group", title=None))
    .mark_bar()
)

sera_date_chart = (
    sera_base
    .encode(
        alt.X(
            "yearmonth(collection_date_numerical)",
            title="collection date",
            axis=alt.Axis(format="%b-%Y", labelAngle=270),
            scale=alt.Scale(nice=False, padding=3),
        ),
        alt.Y("count()", title="number of sera", scale=alt.Scale(nice=False, padding=3)),
    )
    .resolve_scale(y="independent")
    .properties(height=80, width=80)
)

sera_age_chart = (
    sera_base
    .encode(
        alt.X(
            "age_years",
            title="age (years)",
            bin=alt.Bin(step=5, anchor=0),
            scale=alt.Scale(nice=False, padding=3),
        ),
        alt.Y("count()", title="number of sera", scale=alt.Scale(nice=False, padding=3)),
    )
    .resolve_scale(y="independent")
    .properties(height=80, width=130)
)

sera_chart = (
    alt.hconcat(sera_date_chart, sera_age_chart)
    .configure_axis(grid=False, titleFontWeight="normal")
    .configure_header(
        title=None, labelOrient="top", labelFontSize=11, labelPadding=2
    )
    .configure_facet(spacing=7)
    .properties(
        title=alt.TitleParams(
            "collection dates and subject ages for sera",
            anchor="middle",
        ),
    )
)

sera_chart

alt.HConcatChart(...)